### ISSUE TITLE
Error on registration 

### ISSUE THREAD

**Issue by mraak** [douglascorrea/react-hot-redux-firebase-starter#22]
Registration is successful but I still get the following in the console:

> RegistrationPage.js:36 Uncaught TypeError: Cannot read property 'then' of undefined

**Comment by douglascorrea** [comment]
I will take a look at it next week

**Comment by drewrawitz** [comment]
I was getting this same error.  To fix it, go to **authActions.js** and look for the `createUserWithEmailAndPassword` function and replace the following:

From:

``` js
firebaseApi.createUserWithEmailAndPassword(user).then(user => {
```

To:

``` js
return firebaseApi.createUserWithEmailAndPassword(user).then(user => {
```

It was just missing the return. Simple fix! Should work as expected now.

**Comment by douglascorrea** [comment]
thanks @drewrawitz could you create a Pull Request for it? :)

**Comment by drewrawitz** [comment]
@douglascorrea Sure thing. Do I have access to do that? I'm trying to push up my branch but I'm getting some permission errors.

**Comment by douglascorrea** [comment]
@drewrawitz you need to fork this repo, then clone the forked repo in your machine, then change and push to your fork repo, then open a PR from your fork to this repo:

https://gist.github.com/Chaser324/ce0505fbed06b947d962

:)

**Comment by drewrawitz** [comment]
Thanks @douglascorrea! This is my first pull request 😄 I went ahead and submitted it.

**Comment by douglascorrea** [comment]
Perfect! Thanks @drewrawitz  :) 👍 👍 👍
